### PR TITLE
add getting data with APIs project

### PR DESCRIPTION
**Pull request by melrbischoff**

### CODE REVIEW

**Review by kennylee15 — COMMENTED** [review]
Please add links to resources you want to add to resources folder in the main rmd file. Either add the files to resources or a link to an external site.

**Comment by melrbischoff** [comment]
@kennylee15 before I had just linked to the resources file I created which had the final tutorial pdf and the 2 code reference files. I just changed it to link to each individually. Let me know how this looks.

**Review by kennylee15 — COMMENTED** [review]
I checked your changes. Would you mind following this format for links? Github will deal with the root directory automatically. 

Test Photo

**Comment by melrbischoff** [comment]
oh cool! didn't realize that was a thing. just changed. let me know if that's ok, thanks!

**Comment by kennylee15** [comment]
Thanks a lot! 🎉

**Comment by kennylee15** [comment]
@jtr13 @tracy3057  This has a common problem I have been noticing. The embedded object related to the markdown link format for PDF does not get displayed well.  Any advice on alternatives?

See the deployed page:
https://jtr13.github.io/cc21/getting-data-using-apis.html

Thanks!

**Comment by tracy3057** [comment]
Do you just want links? If so, I've deleted the "!" symbol and it can show
up properly now.
[image: image.png]
Bests,
Tracy
Xiny (Tracy) Liu
Columbia University
M.S. in Data Science
https://www.linkedin.com/in/xinyi-liu-0428/
***@***.***; (86) 15850508779

**Comment by kennylee15** [comment]
This is perfect! Thank you!

**Pull request merged**
