### PR TITLE
Translation of visualizations that really work chinese

### PR DESCRIPTION
**Pull request by JFLR12**
plz review it

### CODE REVIEW

**Review by jenn2325 — CHANGES_REQUESTED** [review]
There should be only ONE .Rmd file.  It looks like there are 2 duplicated rmd file here.

**Comment by jenn2325** [comment]
Thanks for your contribution!

**Review by jenn2325 — COMMENTED** [review]
.Rmd filename can only contain lowercase letters. (Otherwise the filenames do not sort nicely on the repo home page. Could you please change the rmd file  name all to lowercases?
@kennylee15  I merged this file before realizing this problem. Is there anyway to revert? Thanks!

**Comment by JFLR12** [comment]
Hi
,I am trying to change my file name, but I can not find my file in pull
request list.

best

Jing

**Pull request merged**
