### PR TITLE
Ellenchen

### PR DESCRIPTION
**Pull request by EllenChen5**

### CODE REVIEW

**Comment by EllenChen5** [comment]
I edit my branch.

**Review by anyunshan — CHANGES_REQUESTED** [review]
Hi Ellen,

It seems that you are adding two Rmd files that differs only in the file name. You can remove one of them as the contents are the same and just leave one Rmd file.

**Comment by anyunshan** [comment]
Hi Ellen,

I just edited your file so the format is good now and I will merge both your Rmd files into, and delete one one them later after merging, the main branch. I think there wouldn't be any other problem. Thanks for the contribution!

**Comment by anyunshan** [comment]
Hi Ellen,

One another issue, I think for all your codes that are trying to import an image, like `knitr::include_graphics("powerbi_logo.png")`
you are do it without providing the image to the resources folder and the building process receives an error as not finding such an image called 'powerbi_logo.png'. Please refer to step 6 of 2.3(https://jtr13.github.io/cc21/github-submission-instructions.html#submission-steps), create a new folder under `resorurce/`,upload all your photos to that new folder and change all your image settings in Rmd file to the proper format according to step 6 of 2.3 above. 

@EllenChen5

**Pull request merged**
