### PR TITLE
ggplot2 tutorial in korean

### PR DESCRIPTION
**Pull request by opszzq**

### CODE REVIEW

**Review by jenn2325 — CHANGES_REQUESTED** [review]
Please make a few changes. I left in-line comments. Thanks!

**Comment by jenn2325** [comment]
A friendly reminder that the CC is due tomorrow, please review this when you get a chance : )

**Comment by opszzq** [comment]
Hi,

It was fixed based on comment.

Thank you,

**Comment by jenn2325** [comment]
Thanks for your contribution!

**Pull request merged**
