### PR TITLE
Chinese Translation EDA and Data Visualization

### PR DESCRIPTION
**Pull request by Ruoxiiiii**
Add contribution to STAT5702

### CODE REVIEW

**Review by anyunshan — CHANGES_REQUESTED** [review]
Start with a single hashtag on the first line.
empty line for the second line.
author info on the third line.

**Review by anyunshan — CHANGES_REQUESTED** [review]
Use single hashtag for first line ONLY.

You can use multiple hashtag for other lines(creating big titles), like "### This is you text"

**Comment by Ruoxiiiii** [comment]
> Use single hashtag for first line ONLY.
> 
> You can use multiple hashtag for other lines(creating big titles), like "### This is you text"

Thanks for let me know! I've changed it following the

**Comment by Ruoxiiiii** [comment]
> Start with a single hashtag on the first line.
> empty line for the second line.
> author info on the third line.

Thanks for let me know! I've changed it following this format.

**Comment by anyunshan** [comment]
Hi Ruoxi,

I think you closed the request last time so I reopen it so that we can process the request. I see the Rmd file hasn't changed, maybe you can update the file following previous comment and commit those updates. Then we can start processing your file

**Comment by Ruoxiiiii** [comment]
Thanks for letting me know! It should work this time :)

**Review by anyunshan — CHANGES_REQUESTED** [review]
I think you still have the wrong format. Make sure you delete all default lines from Rmd file as well, i.e. the "--- title, author, date, output---" stuff should be removed and the Rmd file should strictly beginnng with **hashtag Chinese Translation Exploratory...**

**Comment by Ruoxiiiii** [comment]
Thanks for letting me know! Have edited!

Ruoxi

**Review by anyunshan — CHANGES_REQUESTED** [review]
Hi Ruoxi,

The first line works fine now. For the third line, I would suggest you to write your group's name as you are the one who contribute to our class page and write author's info after that. We are going to put your cc under the translation part so others would know this is originally written by someone else and you are doing the translating work.

**Comment by Ruoxiiiii** [comment]
Hi Anyun,

Sorry for missing your response, I've switched the lines for author info
and group's name.

Thanks,
Ruoxi

**Review by yaojiaye00 — COMMENTED** [review]
Hi, a few comments about the format of the title and file name.
1. The file name can only contain lowercase letters, so please change the file name.
2. A single hashtag should be followed by a single whitespace in the first line
(e.g. # Chinese Translation Exploratory Data Analysis and Data Visualization). Please change it.

**Review by yaojiaye00 — CHANGES_REQUESTED** [review]
Sorry for forgetting to click request changes button. Please change the rmd as indicated in the last comment.

**Comment by anyunshan** [comment]
Hi Ruoxi,

I just edited your first line and I'll merge your request and rename the Rmd file a little bit(like "translation to Chinese xxx") to make it work on the repo page.

Thanks for your contribution!

**Comment by Ruoxiiiii** [comment]
Sure! Thanks so much for your help!

**Pull request merged**
