### PR TITLE
Xinzhe

### PR DESCRIPTION
**Pull request by Xinzhe-Qi**

### CODE REVIEW

**Review by mitali004 — CHANGES_REQUESTED** [review]
The file format is perfect, just you need to change the rmd file name as it should only contain lower case letters and _ so that it can be rendered with no hiccups. Please change the file name (remove 3) and then the pull request is good to go after that. Thanks!

**Comment by Xinzhe-Qi** [comment]
> The file format is perfect, just you need to change the rmd file name as it should only contain lower case letters and _ so that it can be rendered with no hiccups. Please change the file name (remove 3) and then the pull request is good to go after that. Thanks!

**Review by mitali004 — CHANGES_REQUESTED** [review]
The new changes are good! But I still see the previous file too. So there are 2 rmd files right now. Just delete the initial 3d file and then we are good to go!

Thanks again!

**Comment by Xinzhe-Qi** [comment]
> The new changes are good! But I still see the previous file too. So there are 2 rmd files right now. Just delete the initial 3d file and then we are good to go!
> 
> Thanks again!

Hi,

I commit the deletion. I'm pretty new to git, not sure whether it's working now. Thanks!

**Review by mitali004 — APPROVED** [review]

**Comment by mitali004** [comment]
All good! Thanks for your contribution!!

**Pull request merged**
