### PR TITLE
submit CC

### PR DESCRIPTION
**Pull request by zc2583**

### CODE REVIEW

**Comment by jtr13** [comment]
testing

**Review by mitali004 — CHANGES_REQUESTED** [review]
Please use only lower case letters and _ in your rmd file  name. There are two options to add additional files eg pdf in you case. If you are giving an external link do not add the files. If the file is added in resources folder, in your rmd mention the as [Test Photo](resources/sample_project/election.jpg) as show in sample project https://jtr13.github.io/cc21/github-submission-instructions.html. Please make this two changes.
Thanks

**Comment by zc2583** [comment]
1. change the file to lower case
2. delete the file in resources. include only the link in the rmd file.

**Review by mitali004 — APPROVED** [review]

**Comment by mitali004** [comment]
Thanks for your contribution !!

**Pull request merged**
